<h2 style="font-size: 24px; font-weight: bold; color: #2E86AB; margin-bottom: 15px;">3.3.1 A simple self-attention mechanism without trainable weights</h2>

In [2]:
import torch
inputs = torch.tensor(
[[0.43, 0.15, 0.89], # Your (x1)
[0.55, 0.87, 0.66], # journey (x2)
[0.57, 0.85, 0.64], # starts (x3)
[0.22, 0.58, 0.33], # with (x4)
[0.77, 0.25, 0.10], # one (x5)
[0.05, 0.80, 0.55]] # step (x6)
)

In [3]:
query = inputs[0]
attn_scores_2 = torch.empty(inputs.shape[0])
for i,x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(query,x_i)
print(attn_scores_2)

tensor([0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310])


<h3 style="font-size: 20px; font-weight: bold; color: #4A90A4; margin-bottom: 12px;">Normalize</h3>

In [10]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)
attn_weights2_naive = softmax_naive(attn_scores_2)
print(attn_weights2_naive)

attn_weights2 = torch.softmax(attn_scores_2, dim=0)
print(attn_weights2)


tensor([0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452])
tensor([0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452])


In [12]:
query = inputs[1]
context_vec_2 = torch.zeros(query.shape)
for i,x_i in enumerate(inputs):
    context_vec_2 += attn_weights2[i] * x_i
print(context_vec_2)

tensor([0.4421, 0.5931, 0.5790])


<h2 style="font-size: 24px; font-weight: bold; color: #2E86AB; margin-bottom: 15px;">3.3.2 Computing attention weights for all input tokens</h2>

In [14]:
attn_scores = inputs @ inputs.T
attn_scores = torch.softmax(attn_scores, dim=-1)
attn_scores =  attn_scores @ inputs
print(attn_scores)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


<h2 style="font-size: 24px; font-weight: bold; color: #2E86AB; margin-bottom: 15px;">3.4 Implementing self-attention with trainable weights</h2>